version: "2"
services: 

  db:
    build: 
      context: .
    ports:
      - "80:3001"
    # link ไปที่ mongo container
    links:
      - mongo
      
  client: 
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:3000

  # Container ชื่อ mongos
  mongo:
      image: mongo
      ports:
        - "27017:27017"